/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrollmentsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author natha
 */
public class AdminScreen extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    /**
     * Creates new form AdminScreen
     */
    public AdminScreen() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblApplicant = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLRN = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        lblMiddlename = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblExamresult = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnEnroll = new javax.swing.JButton();
        lblEnrollto = new javax.swing.JLabel();
        txtExamscore = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtStudentno = new javax.swing.JTextField();
        SLastname = new javax.swing.JLabel();
        SFirstname = new javax.swing.JLabel();
        SMiddlename = new javax.swing.JLabel();
        SGWA = new javax.swing.JLabel();
        SStatus = new javax.swing.JLabel();
        SEnrollto = new javax.swing.JLabel();
        SSearch = new javax.swing.JButton();
        SCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        SStudents = new javax.swing.JTable();
        SEnroll = new javax.swing.JButton();
        SRemove = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cmbCourse = new javax.swing.JComboBox();
        cmbYearSem = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        lblCompleted = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        SCourse = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSignout = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        tblApplicant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        tblApplicant.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tblApplicant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblApplicant);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 280, 925, 240);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("LIST OF APPLICANTS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 256, 142, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("LRN:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(61, 39, 23, 14);

        txtLRN.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(txtLRN);
        txtLRN.setBounds(90, 36, 177, 20);

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.setContentAreaFilled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch);
        btnSearch.setBounds(277, 37, 47, 19);

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.setContentAreaFilled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);
        btnCancel.setBounds(330, 37, 47, 19);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("LASTNAME:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(542, 17, 59, 19);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("FIRSTNAME:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(541, 44, 60, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("MIDDLENAME:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(531, 69, 68, 14);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("EXAM SCORE:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(528, 92, 70, 14);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("EXAM RESULT:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(524, 115, 74, 14);

        lblLastname.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblLastname.setText(" ");
        jPanel1.add(lblLastname);
        lblLastname.setBounds(607, 19, 161, 14);

        lblFirstname.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblFirstname.setText(" ");
        jPanel1.add(lblFirstname);
        lblFirstname.setBounds(607, 44, 140, 14);

        lblMiddlename.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblMiddlename.setText(" ");
        jPanel1.add(lblMiddlename);
        lblMiddlename.setBounds(605, 69, 140, 14);

        lblStatus.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblStatus.setText(" ");
        jPanel1.add(lblStatus);
        lblStatus.setBounds(606, 139, 147, 14);

        lblExamresult.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblExamresult.setText(" ");
        jPanel1.add(lblExamresult);
        lblExamresult.setBounds(604, 115, 140, 14);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel14.setText("STATUS :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(551, 137, 47, 16);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel15.setText("ENROLL TO:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(538, 159, 60, 14);

        btnEnroll.setBackground(new java.awt.Color(255, 255, 255));
        btnEnroll.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnEnroll.setText("ENROLL");
        btnEnroll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnroll.setContentAreaFilled(false);
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnroll);
        btnEnroll.setBounds(679, 179, 65, 35);

        lblEnrollto.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblEnrollto.setText(" ");
        jPanel1.add(lblEnrollto);
        lblEnrollto.setBounds(604, 159, 140, 14);

        txtExamscore.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(txtExamscore);
        txtExamscore.setBounds(604, 89, 147, 20);

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnUpdate.setText("RESULT");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(761, 89, 43, 20);

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.setContentAreaFilled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);
        btnEdit.setBounds(810, 89, 43, 20);

        btnDrop.setBackground(new java.awt.Color(255, 255, 255));
        btnDrop.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnDrop.setText("REMOVE");
        btnDrop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDrop.setContentAreaFilled(false);
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });
        jPanel1.add(btnDrop);
        btnDrop.setBounds(750, 179, 63, 35);

        jTabbedPane1.addTab("Applicants", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setText("STUDENT NO.:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel10.setText("LASTNAME:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel11.setText("FIRSTNAME:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel12.setText("MIDDLENAME:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel13.setText("GWA:");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel17.setText("STATUS:");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel18.setText("ENROLL TO:");

        txtStudentno.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        SLastname.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        SLastname.setText(" ");

        SFirstname.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        SFirstname.setText(" ");

        SMiddlename.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        SMiddlename.setText(" ");

        SGWA.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        SGWA.setText(" ");

        SStatus.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        SStatus.setText(" ");

        SEnrollto.setText(" ");

        SSearch.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        SSearch.setText("SEARCH");
        SSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SSearch.setContentAreaFilled(false);
        SSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSearchActionPerformed(evt);
            }
        });

        SCancel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        SCancel.setText("CANCEL");
        SCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SCancel.setContentAreaFilled(false);
        SCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCancelActionPerformed(evt);
            }
        });

        SStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(SStudents);

        SEnroll.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        SEnroll.setText("ENROLL");
        SEnroll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SEnroll.setContentAreaFilled(false);
        SEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEnrollActionPerformed(evt);
            }
        });

        SRemove.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        SRemove.setText("REMOVE");
        SRemove.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SRemove.setContentAreaFilled(false);
        SRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SRemoveActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel16.setText("SELECT COURSE:");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel19.setText("SELECT YEAR AND SEM:");

        cmbCourse.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---CHOOSE---" }));
        cmbCourse.setBorder(null);
        cmbCourse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCourseItemStateChanged(evt);
            }
        });

        cmbYearSem.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cmbYearSem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---CHOOSE---" }));
        cmbYearSem.setBorder(null);
        cmbYearSem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbYearSemItemStateChanged(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("ENROLLED STUDENTS");

        lblCompleted.setText(" ");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel21.setText("COURSE:");

        SCourse.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        SCourse.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStudentno, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SCancel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbCourse, 0, 142, Short.MAX_VALUE)
                                    .addComponent(cmbYearSem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SMiddlename, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(SGWA, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCompleted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(SLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(SEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(SRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(SEnrollto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtStudentno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SSearch)
                                .addComponent(SCancel))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(SCourse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(SLastname))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SFirstname)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SMiddlename)
                    .addComponent(jLabel12))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SGWA)
                            .addComponent(lblCompleted))))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(cmbYearSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(SStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(SEnrollto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        jTabbedPane1.addTab("Students", jPanel2);

        jPanel4.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 70, 960, 480);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnSignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Pictures/clear(1).png"))); // NOI18N
        btnSignout.setContentAreaFilled(false);
        btnSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSignout, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel3);
        jPanel3.setBounds(870, 0, 90, 40);

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 51));
        jLabel22.setText("SIGNOUT");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(880, 40, 70, 30);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRATOR");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 0, 451, 50);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Pictures/adminscreenbg.jpg"))); // NOI18N
        jPanel4.add(jLabel24);
        jLabel24.setBounds(0, 0, 960, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoutActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Confirm Sign Out?", 
                        "Sign Out", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_NO_OPTION){
            AdminSignIn asi = new AdminSignIn();
            asi.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnSignoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btnCancel.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnEdit.setEnabled(false);
        btnEnroll.setEnabled(false);
        btnDrop.setEnabled(false);
        txtExamscore.setEnabled(false);
        showtable("SELECT LRN, LASTNAME, FIRSTNAME, MIDDLENAME, COURSE_CODE, COLLEGE_CODE, STATUS_CODE, "
                + "EXAMSCORE, EXAMRESULT FROM APPLICANT");
        SCancel.setEnabled(false);
        SEnroll.setEnabled(false);
        SRemove.setEnabled(false);
        combo();
    }//GEN-LAST:event_formWindowOpened

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "SELECT * FROM APPLICANT WHERE LRN = '"+txtLRN.getText().trim()+"'";
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            
            if(rs.next()){
                lblLastname.setText(rs.getString("LASTNAME"));
                lblFirstname.setText(rs.getString("FIRSTNAME"));
                lblMiddlename.setText(rs.getString("MIDDLENAME"));
                if(rs.getString("EXAMSCORE") == null){
                    btnUpdate.setEnabled(true);
                    btnEdit.setEnabled(false);
                    txtExamscore.setEnabled(true);
                    btnEnroll.setEnabled(false);
                    btnDrop.setEnabled(false);
                }
                else{
                    txtExamscore.setText(rs.getString("EXAMSCORE"));
                    txtExamscore.setEnabled(false);
                    lblExamresult.setText(rs.getString("EXAMRESULT"));
                    btnUpdate.setEnabled(false);
                    btnEdit.setEnabled(true);
                    btnEnroll.setEnabled(true);
                    btnDrop.setEnabled(true);
                    
                }
                lblStatus.setText(rs.getString("STATUS_CODE"));
                lblEnrollto.setText("1stYear-1stSem");
                btnCancel.setEnabled(true);
                btnSearch.setEnabled(false);
                txtLRN.setEnabled(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid LRN");
                txtLRN.setText("");
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        clearAll();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnEdit.setEnabled(true);
        btnUpdate.setEnabled(false);
        if(txtExamscore.getText().compareTo("75") < 0)
            lblExamresult.setText("FAILED");
        else
            lblExamresult.setText("PASSED");
        txtExamscore.setEnabled(false);
        btnEnroll.setEnabled(true);
        btnDrop.setEnabled(true);
        try{
            String sql = "UPDATE APPLICANT SET EXAMSCORE = '"+txtExamscore.getText().trim()+"', "
                    + "EXAMRESULT = '"+lblExamresult.getText().trim()+"' WHERE LRN = '"+txtLRN.getText().trim()+"'";
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Exam Result Updated");
            showtable("SELECT LRN, LASTNAME, FIRSTNAME, MIDDLENAME, COURSE_CODE, COLLEGE_CODE, STATUS_CODE, "
                + "EXAMSCORE, EXAMRESULT FROM APPLICANT");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        btnEnroll.setEnabled(true);
        btnDrop.setEnabled(true);
        btnEdit.setEnabled(false);
        btnUpdate.setEnabled(true);
        txtExamscore.setEnabled(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Remove Applicant?", 
                        "Confirmation", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_NO_OPTION){
            try{
                String sql = "DELETE FROM APPLICANT WHERE LRN = '"+txtLRN.getText().trim()+"'";
                conn = ConnectDB.Connect();
                ps = conn.prepareStatement(sql);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Applicant removed");
                clearAll();
                showtable("SELECT LRN, LASTNAME, FIRSTNAME, MIDDLENAME, COURSE_CODE, COLLEGE_CODE, STATUS_CODE, "
                + "EXAMSCORE, EXAMRESULT FROM APPLICANT");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_btnDropActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        // TODO add your handling code here:
        EnrollNew en = new EnrollNew();
        en.setVisible(true);
        btnCancel.setEnabled(false);
        btnEdit.setEnabled(false);
        btnEnroll.setEnabled(false);
        en.lblSem.setText("1st");
        en.lblStatus.setText("1stYear-1stSem");
        try{
            String str = "SELECT applicant.lastname, applicant.firstname, applicant.middlename, "
                    + "applicant.age, applicant.address, applicant.birthday, applicant.placeofbirth, "
                    + "applicant.gender, college.collegedescription, course.coursedescription, applicant.status_code, "
                    + "applicant.examscore, applicant.examresult FROM APPLICANT "
                    + "INNER JOIN college ON applicant.college_code=college.college_code "
                    + "INNER JOIN course ON applicant.course_code=course.course_code "
                    + "WHERE LRN = '"+txtLRN.getText().trim()+"'";
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(str);
            rs = ps.executeQuery();
            if(rs.next())
            {
                en.lblLastname.setText(rs.getString("LASTNAME"));
                en.lblFirstname.setText(rs.getString("FIRSTNAME"));
                en.lblMiddlename.setText(rs.getString("MIDDLENAME"));
                en.lblAge.setText(rs.getString("AGE"));
                en.lblBirthday.setText(rs.getString("BIRTHDAY"));
                en.lblAddress.setText(rs.getString("ADDRESS"));
                en.lblPlaceofbirth.setText(rs.getString("PLACEOFBIRTH"));
                en.lblGender.setText(rs.getString("GENDER"));
                en.lblCollege.setText(rs.getString("COLLEGEDESCRIPTION"));
                en.lblCourse.setText(rs.getString("COURSEDESCRIPTION"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void SSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSearchActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "SELECT * FROM STUDENT WHERE STUDENTNUMBER = '"+txtStudentno.getText().trim()+"'";
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            
            if(rs.next()){
                SCourse.setText(rs.getString("COURSE_CODE"));
                SLastname.setText(rs.getString("LASTNAME"));
                SFirstname.setText(rs.getString("FIRSTNAME"));
                SMiddlename.setText(rs.getString("MIDDLENAME"));
                
                SStatus.setText(rs.getString("STATUS_CODE"));
                if(rs.getString("STATUS_CODE").equals("1stYear-1stSem"))
                    SEnrollto.setText("1stYear-2ndSem");
                else if(rs.getString("STATUS_CODE").equals("1stYear-2ndSem"))
                    SEnrollto.setText("2ndYear-1stSem");
                else if(rs.getString("STATUS_CODE").equals("2ndYear-1stSem"))
                    SEnrollto.setText("2ndYear-2ndSem");
                else if(rs.getString("STATUS_CODE").equals("2ndYear-2ndSem"))
                    SEnrollto.setText("3rdYear-1stSem");
                else if(rs.getString("STATUS_CODE").equals("3rdYear-1stSem"))
                    SEnrollto.setText("3rdYear-2ndSem");
                else if(rs.getString("STATUS_CODE").equals("3rdYear-2ndSem"))
                    SEnrollto.setText("4thYear-1stSem");
                else if(rs.getString("STATUS_CODE").equals("4thYear-1stSem"))
                    SEnrollto.setText("4thYear-2ndSem");
                else if(rs.getString("STATUS_CODE").equals("4thYear-2ndSem"))
                    SEnrollto.setText("5thYear-1stSem");
                else if(rs.getString("STATUS_CODE").equals("5thYear-1stSem"))
                    SEnrollto.setText("5thYear-2ndSem");
                
                SCancel.setEnabled(true);
                SSearch.setEnabled(false);
                txtStudentno.setEnabled(false);
                gwa();
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Student Number");
                txtStudentno.setText("");
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SSearchActionPerformed

    private void SCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCancelActionPerformed
        // TODO add your handling code here:
        clearAll("clear");
    }//GEN-LAST:event_SCancelActionPerformed

    private void SRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SRemoveActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Remove Student?", 
                        "Confirmation", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_NO_OPTION){
            try{
                String sql = "DELETE FROM STUDENT WHERE STUDENTNUMBER = '"+txtStudentno.getText().trim()+"'";
                conn = ConnectDB.Connect();
                ps = conn.prepareStatement(sql);
                ps.executeUpdate();
                removegrades();
                JOptionPane.showMessageDialog(null, "Student removed");
                clearAll("clear");
                sshowtable("SELECT STUDENTNUMBER, LASTNAME, FIRSTNAME, MIDDLENAME, COURSE_CODE, COLLEGE_CODE, STATUS_CODE, "
                + "PASSWORD FROM STUDENT WHERE COURSE_CODE = '"
                +cmbCourse.getSelectedItem().toString()+"' AND STATUS_CODE = '"
                +cmbYearSem.getSelectedItem().toString()+"'");
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_SRemoveActionPerformed

    private void cmbCourseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCourseItemStateChanged
        // TODO add your handling code here:
        sshowtable("SELECT STUDENTNUMBER, LASTNAME, FIRSTNAME, MIDDLENAME, COURSE_CODE, COLLEGE_CODE, STATUS_CODE, "
                + "PASSWORD FROM STUDENT WHERE COURSE_CODE = '"
                +cmbCourse.getSelectedItem().toString()+"' AND STATUS_CODE = '"
                +cmbYearSem.getSelectedItem().toString()+"'");
    }//GEN-LAST:event_cmbCourseItemStateChanged

    private void cmbYearSemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbYearSemItemStateChanged
        // TODO add your handling code here:
        sshowtable("SELECT STUDENTNUMBER, LASTNAME, FIRSTNAME, MIDDLENAME, COURSE_CODE, COLLEGE_CODE, STATUS_CODE, "
                + "PASSWORD FROM STUDENT WHERE COURSE_CODE = '"
                +cmbCourse.getSelectedItem().toString()+"' AND STATUS_CODE = '"
                +cmbYearSem.getSelectedItem().toString()+"'");
    }//GEN-LAST:event_cmbYearSemItemStateChanged

    private void SEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEnrollActionPerformed
        // TODO add your handling code here:
        String subject;
        if(JOptionPane.showConfirmDialog(null, "Confirm Enrollment?", 
                            "Confirmation", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_NO_OPTION){
            try{
                conn = ConnectDB.Connect();
                ps = conn.prepareStatement("SELECT SUBJECT_CODE FROM SUBJECT WHERE COURSE_CODE = '"
                        +SCourse.getText()+"' AND STATUS_CODE = '" +SEnrollto.getText()+"'");
                rs = ps.executeQuery();
                
                while(rs.next()){
                    subject = rs.getString("SUBJECT_CODE");
                    ps = conn.prepareStatement("INSERT INTO GRADES (STUDENTNUMBER, SUBJECT_CODE, STATUS_CODE) "
                            +"VALUES ('"+txtStudentno.getText()+"', '"
                            +subject+"', '"+SEnrollto.getText()+"')");
                    ps.executeUpdate();
                    System.out.println("eyy");
                }

                String sql = "UPDATE STUDENT SET STATUS_CODE = '"+SEnrollto.getText()+"' "
                        + "WHERE STUDENTNUMBER = '"+txtStudentno.getText().trim()+"'";
                ps = conn.prepareStatement(sql);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Student Successfully Enrolled");
                clearAll("clear");
                sshowtable("SELECT STUDENTNUMBER, LASTNAME, FIRSTNAME, MIDDLENAME, COURSE_CODE, COLLEGE_CODE, STATUS_CODE, "
                    + "PASSWORD FROM STUDENT WHERE COURSE_CODE = '"
                    +cmbCourse.getSelectedItem().toString()+"' AND STATUS_CODE = '"
                    +cmbYearSem.getSelectedItem().toString()+"'");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_SEnrollActionPerformed
    
    public void gwa(){
        int ctr = 0;
        double ave = 0.0, sgrade = 0.0;
        boolean flag = false;
        String aves;
        try{
            String sql = "SELECT SUBJECTGRADE FROM GRADES WHERE STUDENTNUMBER = '"
                    +txtStudentno.getText()+"' AND STATUS_CODE = '"
                    +SStatus.getText()+"'";
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next()){
                if(rs.getString("SUBJECTGRADE") == null){
                    flag = true;
                }
                else{
                    sgrade = Double.parseDouble(rs.getString("SUBJECTGRADE"));
                    ave += sgrade;
                    ctr++;
                }
            }
            if(flag == true){
                lblCompleted.setText("Incomplete Grades");
            }
            else{
                SEnroll.setEnabled(true);
                SRemove.setEnabled(true);
                lblCompleted.setText("Complete Grades");
            }
            ave = Math.round((ave/ctr) * 100.0)/100.0;
            aves = Double.toString(ave);
            SGWA.setText(aves);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void removegrades(){
        try{
            String sql = "DELETE FROM GRADES WHERE STUDENTNUMBER = '"+txtStudentno.getText().trim()+"'";
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            ps.executeUpdate();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public void combo(){
        try{
            String sql, str;
            sql = "SELECT COURSE_CODE FROM COURSE";
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
                cmbCourse.addItem(rs.getString("COURSE_CODE"));
            }
            
            str = "SELECT STATUS_CODE FROM STATUS";
            ps = conn.prepareStatement(str);
            rs = ps.executeQuery();
            
            while(rs.next()){
                if(!rs.getString("STATUS_CODE").equals("Applicant")){
                    cmbYearSem.addItem(rs.getString("STATUS_CODE"));
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void clearAll(){
        txtLRN.setEnabled(true);
        txtLRN.setText("");
        lblLastname.setText("");
        lblFirstname.setText("");
        lblMiddlename.setText("");
        txtExamscore.setText("");
        txtExamscore.setEnabled(false);
        lblExamresult.setText("");
        lblStatus.setText("");
        lblEnrollto.setText("");
        btnSearch.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnEdit.setEnabled(false);
        btnEnroll.setEnabled(false);
        btnDrop.setEnabled(false);
        btnCancel.setEnabled(false);
    }
    
    public void clearAll(String str){
        txtStudentno.setEnabled(true);
        txtStudentno.setText("");
        SLastname.setText("");
        SFirstname.setText("");
        SMiddlename.setText("");
        SGWA.setText("");
        SStatus.setText("");
        SEnrollto.setText("");
        SSearch.setEnabled(true);
        SEnroll.setEnabled(false);
        SRemove.setEnabled(false);
        SCancel.setEnabled(false);
        lblCompleted.setText("");
        SCourse.setText("");
    }
    
    public void showtable(String sql){
        try{
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            tblApplicant.setModel(DbUtils.resultSetToTableModel(rs));
            tblApplicant.setEnabled(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void sshowtable(String sql){
        try{
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            SStudents.setModel(DbUtils.resultSetToTableModel(rs));
            SStudents.setEnabled(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SCancel;
    private javax.swing.JLabel SCourse;
    private javax.swing.JButton SEnroll;
    private javax.swing.JLabel SEnrollto;
    private javax.swing.JLabel SFirstname;
    private javax.swing.JLabel SGWA;
    private javax.swing.JLabel SLastname;
    private javax.swing.JLabel SMiddlename;
    private javax.swing.JButton SRemove;
    private javax.swing.JButton SSearch;
    private javax.swing.JLabel SStatus;
    private javax.swing.JTable SStudents;
    public javax.swing.JButton btnCancel;
    public javax.swing.JButton btnDrop;
    public javax.swing.JButton btnEdit;
    public javax.swing.JButton btnEnroll;
    public javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSignout;
    public javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbCourse;
    private javax.swing.JComboBox cmbYearSem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCompleted;
    private javax.swing.JLabel lblEnrollto;
    private javax.swing.JLabel lblExamresult;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblMiddlename;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblApplicant;
    private javax.swing.JTextField txtExamscore;
    private javax.swing.JTextField txtLRN;
    private javax.swing.JTextField txtStudentno;
    // End of variables declaration//GEN-END:variables
}
