/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrollmentsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author natha
 */
public class EnrollNew extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    /**
     * Creates new form EnrollNew
     */
    public EnrollNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblStudentno = new javax.swing.JLabel();
        lblCollege = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        lblSem = new javax.swing.JLabel();
        cmbSY = new javax.swing.JComboBox();
        lblLastname = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnConfirm = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMiddlename = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblBirthday = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPlaceofbirth = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 0), 3, true));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel1.setText("STUDENT NO.:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 40, 63, 14);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel11.setText("SCHOOL YEAR:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 100, 66, 14);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel12.setText("COLLEGE:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 60, 43, 14);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel13.setText("COURSE:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 80, 39, 14);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel14.setText("SEM:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 120, 23, 14);

        lblStudentno.setText(" ");
        jPanel1.add(lblStudentno);
        lblStudentno.setBounds(100, 40, 300, 14);

        lblCollege.setText(" ");
        jPanel1.add(lblCollege);
        lblCollege.setBounds(100, 60, 300, 14);

        lblCourse.setText(" ");
        jPanel1.add(lblCourse);
        lblCourse.setBounds(100, 80, 300, 14);

        lblSem.setText(" ");
        jPanel1.add(lblSem);
        lblSem.setBounds(100, 120, 300, 14);

        cmbSY.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        cmbSY.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---CHOOSE---" }));
        cmbSY.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSYItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbSY);
        cmbSY.setBounds(100, 100, 80, 20);

        lblLastname.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblLastname.setText(" ");
        jPanel1.add(lblLastname);
        lblLastname.setBounds(160, 150, 239, 14);

        jPanel2.setBackground(new java.awt.Color(51, 204, 0));

        btnConfirm.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnConfirm.setText("CONFIRM ENROLL");
        btnConfirm.setContentAreaFilled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(130, 440, 140, 30);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel3.setText("FIRSTNAME         :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 30, 80, 14);

        lblFirstname.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblFirstname.setText(" ");
        jPanel3.add(lblFirstname);
        lblFirstname.setBounds(90, 30, 239, 14);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel4.setText("MIDDLENAME  :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 60, 80, 14);

        lblMiddlename.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblMiddlename.setText(" ");
        jPanel3.add(lblMiddlename);
        lblMiddlename.setBounds(90, 60, 239, 14);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel5.setText("AGE                         :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 90, 80, 14);

        lblAge.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblAge.setText(" ");
        jPanel3.add(lblAge);
        lblAge.setBounds(90, 90, 239, 14);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel6.setText("ADDRESS             :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 120, 71, 14);

        lblAddress.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblAddress.setText(" ");
        jPanel3.add(lblAddress);
        lblAddress.setBounds(90, 120, 239, 14);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel7.setText("BIRTHDAY          :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 150, 70, 14);

        lblBirthday.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblBirthday.setText(" ");
        jPanel3.add(lblBirthday);
        lblBirthday.setBounds(90, 150, 239, 14);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel8.setText("PLACE OF BIRTH:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(0, 180, 75, 14);

        lblPlaceofbirth.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblPlaceofbirth.setText(" ");
        jPanel3.add(lblPlaceofbirth);
        lblPlaceofbirth.setBounds(90, 180, 239, 14);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel9.setText(" GENDER              :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(0, 210, 70, 14);

        lblGender.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblGender.setText(" ");
        jPanel3.add(lblGender);
        lblGender.setBounds(90, 210, 239, 14);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel10.setText("STATUS                 :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(0, 240, 80, 14);

        lblStatus.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblStatus.setText(" ");
        jPanel3.add(lblStatus);
        lblStatus.setBounds(90, 240, 239, 14);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel2.setText("LASTNAME          :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 80, 14);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(50, 150, 350, 280);

        jPanel4.setBackground(new java.awt.Color(51, 204, 0));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ENROLMENT STATUS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 0, 390, 20);

        jPanel5.setBackground(new java.awt.Color(255, 140, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 30, 390, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            String sql = "SELECT * FROM SY";
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next()){
                cmbSY.addItem(rs.getString("SY"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void cmbSYItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSYItemStateChanged
        // TODO add your handling code here:
        String sql, snum;
        boolean flag = false;
        int studentnum;
        conn = ConnectDB.Connect();
        try{
            if(cmbSY.getSelectedItem().toString().equals("2019-2020")){
                studentnum = 201900001;
                snum = Integer.toString(studentnum);
                sql = "SELECT STUDENTNUMBER FROM STUDENT WHERE STUDENTNUMBER = '"+snum+"'";
                ps = conn.prepareStatement(sql);
                rs = ps.executeQuery();
                if(rs.next()){
                    do{
                        snum = Integer.toString(studentnum);
                        sql = "SELECT STUDENTNUMBER FROM STUDENT WHERE STUDENTNUMBER = '"+snum+"'";
                        ps = conn.prepareStatement(sql);
                        rs = ps.executeQuery();
                        if(rs.next()){
                            studentnum += 1;
                        }
                        else{
                            lblStudentno.setText(snum);
                            flag = true;
                        }
                    }while(flag != true);
                }
                else{
                    lblStudentno.setText(snum);
                }
            }
            //
            else if(cmbSY.getSelectedItem().toString().equals("2020-2021")){
                studentnum = 202000001;
                snum = Integer.toString(studentnum);
                sql = "SELECT STUDENTNUMBER FROM STUDENT WHERE STUDENTNUMBER = '"+snum+"'";
                ps = conn.prepareStatement(sql);
                rs = ps.executeQuery();
                if(rs.next()){
                    do{
                        snum = Integer.toString(studentnum);
                        sql = "SELECT STUDENTNUMBER FROM STUDENT WHERE STUDENTNUMBER = '"+snum+"'";
                        ps = conn.prepareStatement(sql);
                        rs = ps.executeQuery();
                        if(rs.next()){
                            studentnum += 1;
                        }
                        else{
                            lblStudentno.setText(snum);
                            flag = true;
                        }
                    }while(flag != true);
                }
                else{
                    lblStudentno.setText(snum);
                }
            }
            //
            else if(cmbSY.getSelectedItem().toString().equals("2021-2022")){
                studentnum = 202100001;
                snum = Integer.toString(studentnum);
                sql = "SELECT STUDENTNUMBER FROM STUDENT WHERE STUDENTNUMBER = '"+snum+"'";
                ps = conn.prepareStatement(sql);
                rs = ps.executeQuery();
                if(rs.next()){
                    do{
                        snum = Integer.toString(studentnum);
                        sql = "SELECT STUDENTNUMBER FROM STUDENT WHERE STUDENTNUMBER = '"+snum+"'";
                        ps = conn.prepareStatement(sql);
                        rs = ps.executeQuery();
                        if(rs.next()){
                            studentnum += 1;
                        }
                        else{
                            lblStudentno.setText(snum);
                            flag = true;
                        }
                    }while(flag != true);
                }
                else{
                    lblStudentno.setText(snum);
                }
            }
            
            else if(cmbSY.getSelectedItem().toString().equals("2022-2023")){
                studentnum = 202200001;
                snum = Integer.toString(studentnum);
                sql = "SELECT STUDENTNUMBER FROM STUDENT WHERE STUDENTNUMBER = '"+snum+"'";
                ps = conn.prepareStatement(sql);
                rs = ps.executeQuery();
                if(rs.next()){
                    do{
                        snum = Integer.toString(studentnum);
                        sql = "SELECT STUDENTNUMBER FROM STUDENT WHERE STUDENTNUMBER = '"+snum+"'";
                        ps = conn.prepareStatement(sql);
                        rs = ps.executeQuery();
                        if(rs.next()){
                            studentnum += 1;
                        }
                        else{
                            lblStudentno.setText(snum);
                            flag = true;
                        }
                    }while(flag != true);
                }
                else{
                    lblStudentno.setText(snum);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            
    }//GEN-LAST:event_cmbSYItemStateChanged

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        String college = "", course = "";
        if(cmbSY.getSelectedItem().toString().equals("---CHOOSE---")){
            JOptionPane.showMessageDialog(null, "Please Select A School Year");
        }
        else{
            if(JOptionPane.showConfirmDialog(null, "Confirm Enrollment?", 
                            "Confirmation", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_NO_OPTION){
                if(lblCollege.getText().equals("College of Engineering and Technology"))
                        college = "CET";
                else if(lblCollege.getText().equals("College of Science"))
                    college = "CS";

                if(lblCourse.getText().equals("BS Computer Science"))
                    course = "BSCS";
                else if(lblCourse.getText().equals("BS Civil Engineering"))
                    course = "BSCE";
                else if(lblCourse.getText().equals("BS Biology"))
                    course = "BSBIO";
                else if(lblCourse.getText().equals("BS Psychology"))
                    course = "BSPSYCH";
                    
                try{
                    String sql = "INSERT INTO STUDENT VALUES ('"
                            +lblStudentno.getText().trim()+"', '"
                            +lblLastname.getText().trim()+"', '"
                            +lblFirstname.getText().trim()+"', '"
                            +lblMiddlename.getText().trim()+"', '"
                            +lblAge.getText().trim()+"', '"
                            +lblAddress.getText().trim()+"', '"
                            +lblBirthday.getText().trim()+"', '"
                            +lblPlaceofbirth.getText().trim()+"', '"
                            +lblGender.getText().trim()+"', '"
                            +college+"', '"
                            +course+"', '"
                            +lblStatus.getText().trim()+"', '123')";
                    ps = conn.prepareStatement(sql);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Enrolled Successfully");
                    Subjects();
                    this.dispose();
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
               
            }
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed
    
    public void Subjects(){
        String faculty, subject, course="";
        try{
            if(lblCourse.getText().equals("BS Computer Science"))
                        course = "BSCS";
                    else if(lblCourse.getText().equals("BS Civil Engineering"))
                        course = "BSCE";
                    else if(lblCourse.getText().equals("BS Biology"))
                        course = "BSBIO";
                    else if(lblCourse.getText().equals("BS Psychology"))
                        course = "BSPSYCH";
            
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement("SELECT SUBJECT_CODE FROM SUBJECT WHERE COURSE_CODE = '"
                    +course+"' AND STATUS_CODE = '" +lblStatus.getText()+"'");
            rs = ps.executeQuery();
            
            while(rs.next()){
                subject = rs.getString("SUBJECT_CODE");
                ps = conn.prepareStatement("INSERT INTO GRADES (STUDENTNUMBER, SUBJECT_CODE, STATUS_CODE) "
                        +"VALUES ('"+lblStudentno.getText()+"', '"
                        +subject+"', '"+lblStatus.getText()+"')");
                ps.executeUpdate();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnrollNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnrollNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnrollNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnrollNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrollNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox cmbSY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JLabel lblAddress;
    public javax.swing.JLabel lblAge;
    public javax.swing.JLabel lblBirthday;
    public javax.swing.JLabel lblCollege;
    public javax.swing.JLabel lblCourse;
    public javax.swing.JLabel lblFirstname;
    public javax.swing.JLabel lblGender;
    public javax.swing.JLabel lblLastname;
    public javax.swing.JLabel lblMiddlename;
    public javax.swing.JLabel lblPlaceofbirth;
    public javax.swing.JLabel lblSem;
    public javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStudentno;
    // End of variables declaration//GEN-END:variables
}
