/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrollmentsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author natha
 */
public class FacultyScreen extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    /**
     * Creates new form FacultyScreen
     */
    public FacultyScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFaculty = new javax.swing.JLabel();
        cmbSubjects = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtStudentno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        lblMiddlename = new javax.swing.JLabel();
        txtMidterm = new javax.swing.JTextField();
        txtFinals = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cmbCourse = new javax.swing.JComboBox();
        btnSearch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        SSubject = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtSubjectCode = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSignout = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel1.setText("FACULTY :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 70, 50, 14);

        lblFaculty.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        lblFaculty.setText(" ");
        jPanel1.add(lblFaculty);
        lblFaculty.setBounds(260, 70, 140, 13);

        cmbSubjects.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        cmbSubjects.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---CHOOSE---" }));
        cmbSubjects.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSubjectsItemStateChanged(evt);
            }
        });
        cmbSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbSubjectsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbSubjectsMouseExited(evt);
            }
        });
        cmbSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSubjectsActionPerformed(evt);
            }
        });
        jPanel1.add(cmbSubjects);
        cmbSubjects.setBounds(620, 340, 150, 20);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel2.setText("SUBJECTS:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(570, 340, 50, 20);

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 364, 1101, 230);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("LIST OF STUDENTS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 340, 110, 17);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel4.setText("SEARCH STUDENT NO.:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 100, 101, 14);

        txtStudentno.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jPanel1.add(txtStudentno);
        txtStudentno.setBounds(260, 100, 143, 19);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel5.setText("LASTNAME:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 130, 54, 14);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel6.setText("FIRSTNAME:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 160, 56, 14);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel7.setText("MIDDLENAME:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 190, 69, 14);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel8.setText("MIDTERM GRADE:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 230, 83, 14);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel9.setText("FINALS GRADE:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(180, 270, 69, 14);

        lblLastname.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        lblLastname.setText(" ");
        jPanel1.add(lblLastname);
        lblLastname.setBounds(260, 130, 143, 13);

        lblFirstname.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        lblFirstname.setText(" ");
        jPanel1.add(lblFirstname);
        lblFirstname.setBounds(260, 160, 143, 13);

        lblMiddlename.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        lblMiddlename.setText(" ");
        jPanel1.add(lblMiddlename);
        lblMiddlename.setBounds(260, 190, 143, 13);

        txtMidterm.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jPanel1.add(txtMidterm);
        txtMidterm.setBounds(260, 230, 143, 19);

        txtFinals.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jPanel1.add(txtFinals);
        txtFinals.setBounds(260, 270, 143, 19);

        btnSubmit.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.setContentAreaFilled(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(360, 300, 41, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel10.setText("COURSE:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 340, 40, 20);

        cmbCourse.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---CHOOSE---" }));
        cmbCourse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCourseItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbCourse);
        cmbCourse.setBounds(400, 340, 160, 20);

        btnSearch.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.setContentAreaFilled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch);
        btnSearch.setBounds(420, 90, 41, 30);

        btnCancel.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.setContentAreaFilled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);
        btnCancel.setBounds(470, 90, 41, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel11.setText("GRADE SELECTED SUBJECT:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(410, 130, 120, 14);

        SSubject.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        SSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---CHOOSE---" }));
        SSubject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SSubjectItemStateChanged(evt);
            }
        });
        jPanel1.add(SSubject);
        SSubject.setBounds(550, 130, 130, 20);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel12.setText("SUBJECT CODE:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(410, 170, 68, 14);

        txtSubjectCode.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        txtSubjectCode.setText(" ");
        jPanel1.add(txtSubjectCode);
        txtSubjectCode.setBounds(490, 170, 147, 13);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("FACULTY");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 0, 250, 57);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("SIGN OUT");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1030, 40, 80, 15);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnSignout.setBackground(new java.awt.Color(255, 255, 255));
        btnSignout.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        btnSignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Pictures/clear(1).png"))); // NOI18N
        btnSignout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSignout.setBorderPainted(false);
        btnSignout.setContentAreaFilled(false);
        btnSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(1020, 0, 90, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentsystem/Pictures/adminscreenbg.jpg"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 0, 1110, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoutActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Confirm Sign Out?",
            "Sign Out", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_NO_OPTION){
            FacultySignIn fsi = new FacultySignIn();
            fsi.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSignoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        course();
        txtMidterm.setEnabled(false);
        txtFinals.setEnabled(false);
        btnCancel.setEnabled(false);
        btnSubmit.setEnabled(false);
        SSubject.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void cmbCourseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCourseItemStateChanged
        // TODO add your handling code here:
        try{
            String sql = "SELECT SUBJECTDESCRIPTION FROM SUBJECT WHERE FACULTY = '"
                    +lblFaculty.getText().trim()+"' AND COURSE_CODE = '"
                    +cmbCourse.getSelectedItem().toString()+"'";
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            cmbSubjects.removeAllItems();
            while(rs.next()){
                cmbSubjects.addItem(rs.getString("SUBJECTDESCRIPTION"));
            }
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_cmbCourseItemStateChanged

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "SELECT STUDENT.LASTNAME, STUDENT.FIRSTNAME, STUDENT.MIDDLENAME, "
                    + "SUBJECT.SUBJECTDESCRIPTION, SUBJECT.COURSE_CODE, SUBJECT.STATUS_CODE FROM SUBJECT "
                    + "INNER JOIN STUDENT ON SUBJECT.COURSE_CODE = STUDENT.COURSE_CODE AND "
                    + "SUBJECT.STATUS_CODE = STUDENT.STATUS_CODE WHERE SUBJECT.FACULTY = '"
                    +lblFaculty.getText()+"' AND STUDENT.STUDENTNUMBER = '" +txtStudentno.getText()+"'";
            
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next()){
               SSubject.addItem(rs.getString("SUBJECTDESCRIPTION"));
               lblLastname.setText(rs.getString("LASTNAME"));
               lblFirstname.setText(rs.getString("FIRSTNAME"));
               lblMiddlename.setText(rs.getString("MIDDLENAME"));
            }
            txtStudentno.setEnabled(false);
            btnSearch.setEnabled(false);
            btnCancel.setEnabled(true);
            SSubject.setEnabled(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cmbSubjectsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSubjectsItemStateChanged
        
    }//GEN-LAST:event_cmbSubjectsItemStateChanged

    private void cmbSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSubjectsActionPerformed

    }//GEN-LAST:event_cmbSubjectsActionPerformed

    private void cmbSubjectsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSubjectsMouseExited

    }//GEN-LAST:event_cmbSubjectsMouseExited

    private void cmbSubjectsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSubjectsMouseEntered
        // TODO add your handling code here:
        String str = "SELECT STUDENT.STUDENTNUMBER, STUDENT.LASTNAME, STUDENT.FIRSTNAME, STUDENT.MIDDLENAME, "
                + "SUBJECT.COURSE_CODE, SUBJECT.STATUS_CODE, SUBJECT.SUBJECTDESCRIPTION FROM SUBJECT "
                + "INNER JOIN STUDENT ON SUBJECT.COURSE_CODE = STUDENT.COURSE_CODE "
                + "AND SUBJECT.STATUS_CODE = STUDENT.STATUS_CODE "
                + "WHERE SUBJECT.FACULTY = '"+lblFaculty.getText()+"' AND SUBJECT.COURSE_CODE = '"
                +cmbCourse.getSelectedItem().toString()+"' AND SUBJECT.SUBJECTDESCRIPTION = '"
                +cmbSubjects.getSelectedItem().toString()+"'";
        showtable(str);
    }//GEN-LAST:event_cmbSubjectsMouseEntered

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtStudentno.setText("");
        lblLastname.setText("");
        lblFirstname.setText("");
        lblMiddlename.setText("");
        txtMidterm.setText("");
        txtFinals.setText("");
        SSubject.removeAllItems();
        btnSearch.setEnabled(true);
        btnCancel.setEnabled(false);
        SSubject.setEnabled(false);
        btnSubmit.setEnabled(false);
        txtSubjectCode.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void SSubjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SSubjectItemStateChanged
        // TODO add your handling code here:
        String str = "", subjectcode = "";
        try{
            String sql = "SELECT SUBJECT_CODE FROM SUBJECT WHERE SUBJECTDESCRIPTION = '"
                    +SSubject.getSelectedItem().toString()+"'";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            
            if(rs.next())
                subjectcode = rs.getString("SUBJECT_CODE");
            
            txtSubjectCode.setText(subjectcode);
            
            str = "SELECT MIDTERM, FINALS FROM GRADES WHERE STUDENTNUMBER = '"+txtStudentno.getText()+"' "
                    + "AND SUBJECT_CODE = '"+subjectcode+"'";
            ps = conn.prepareStatement(str);
            rs = ps.executeQuery();
            
            if(rs.next()){
                if(rs.getString("MIDTERM") == null){
                    txtMidterm.setEnabled(true);
                    txtFinals.setEnabled(true);
                    btnSubmit.setEnabled(true);
                    txtMidterm.setText("");
                    txtFinals.setText("");
                }
                else{
                    txtMidterm.setText(rs.getString("MIDTERM"));
                    txtFinals.setText(rs.getString("FINALS"));
                    btnSubmit.setEnabled(false);
                    txtMidterm.setEnabled(false);
                    txtFinals.setEnabled(false);
                }
            }
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_SSubjectItemStateChanged

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Submit Grades?", 
                        "Confirmation", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_NO_OPTION){
            try{
                double midterm = 0.0, finals = 0.0, finalg = 0.0;
                if(!txtMidterm.getText().equals("") && !txtFinals.getText().equals("")){
                    midterm = Double.parseDouble(txtMidterm.getText().trim());
                    finals = Double.parseDouble(txtFinals.getText().trim());
                    if((midterm * 0.5) + (finals * 0.5) >= 96)
                        finalg = 1.00;
                    else if((midterm * 0.5) + (finals * 0.5) >= 91)
                        finalg = 1.25;
                    else if((midterm * 0.5) + (finals * 0.5) >= 87)
                        finalg = 1.50;
                    else if((midterm * 0.5) + (finals * 0.5) >= 82)
                        finalg = 1.75;
                    else if((midterm * 0.5) + (finals * 0.5) >= 78)
                        finalg = 2.00;
                    else if((midterm * 0.5) + (finals * 0.5) >= 73)
                        finalg = 2.25;
                    else if((midterm * 0.5) + (finals * 0.5) >= 69)
                        finalg = 2.50;
                    else if((midterm * 0.5) + (finals * 0.5) >= 64)
                        finalg = 2.75;
                    else if((midterm * 0.5) + (finals * 0.5) >= 60)
                        finalg = 3.00;
                    else
                        finalg = 5.00;
                    String sql = "UPDATE GRADES SET MIDTERM = '"+Double.toString(midterm)+"', FINALS = '"
                            +Double.toString(finals)+"', SUBJECTGRADE = '"+Double.toString(finalg)+"' "
                            + "WHERE STUDENTNUMBER = '"+txtStudentno.getText()+"' AND SUBJECT_CODE = '"
                            +txtSubjectCode.getText()+"'";
                    conn = ConnectDB.Connect();
                    ps = conn.prepareStatement(sql);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Grades Updated");
                    btnSubmit.setEnabled(false);
                    txtMidterm.setEnabled(false);
                    txtFinals.setEnabled(false);
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    
    public void course(){
        try{
            String sql = "SELECT COURSE_CODE FROM COURSE";
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
                cmbCourse.addItem(rs.getString("COURSE_CODE"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void showtable(String sql){
        try{
            conn = ConnectDB.Connect();
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            tblStudents.setModel(DbUtils.resultSetToTableModel(rs));
            tblStudents.setEnabled(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox SSubject;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSignout;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cmbCourse;
    private javax.swing.JComboBox cmbSubjects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblFaculty;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblMiddlename;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtFinals;
    private javax.swing.JTextField txtMidterm;
    private javax.swing.JTextField txtStudentno;
    private javax.swing.JLabel txtSubjectCode;
    // End of variables declaration//GEN-END:variables
}
